version: "3.8"

services:
  jawk-legal:
    # Imagem publicada automaticamente pelo GitHub Actions no Docker Hub
    image: macega/jawk-legal:latest
    container_name: jawk-legal
    restart: unless-stopped
    ports:
      - "8095:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jawk-legal.rule=Host(`legal.jawk.com.br`)"
      - "traefik.http.routers.jawk-legal.entrypoints=websecure"
      - "traefik.http.routers.jawk-legal.tls.certresolver=letsencrypt"
      - "traefik.http.services.jawk-legal.loadbalancer.server.port=80"
