version: "3.8"

services:
  jawk-legal:
    # Imagem publicada automaticamente pelo GitHub Actions no Docker Hub
    image: macega/jawk-legal:latest
    container_name: jawk-legal
    restart: unless-stopped
    ports:
      - "8095:80"    # O Nginx Proxy Manager vai apontar para esta porta

networks:
  default:
    external: false
